Auth page
NZWhale/wishlist_frontend pull request #1
Opened 2021-04-04 14:41 UTC by NZWhale

2021-04-04 15:33 UTC, zverev requested changes

2021-04-04 15:33 UTC, zverev commented on src/components/RegistrationPage/index.tsx
> +                    <Button
"Enter" doesn't work

2021-04-04 15:33 UTC, zverev commented on src/components/RegistrationPage/index.tsx
> +                    style={{marginTop: "293px"}}
Trash) This is wrong way to display form on the center of the screen. Use flexbox.

2021-04-04 15:33 UTC, zverev commented on src/components/RegistrationPage/sendRegistrationRequest.ts
> +export const sendRegistrationRequest = (email: string) => new Promise((resolve, reject) => {
Just return fetch

2021-04-04 15:33 UTC, zverev commented on src/components/RegistrationPage/sendRegistrationRequest.ts
> +                reject(new Error('Something goes wrong'))
Something goes wrong. Guess what, motherfucker 😏

2021-04-04 15:33 UTC, zverev commented on src/components/RegistrationPage/sendRegistrationRequest.ts
> +                reject(new Error('Invalid credentials'))
App will display this in case of any server error with 500 code, for example if email was not send. By the way "invalid credentials" correspond to 401/403 code.

2021-04-04 15:33 UTC, zverev commented on src/components/RegistrationPage/sendRegistrationRequest.ts
> +            resolve(response.status)
Status is not needed outside.

2021-04-08 18:38 UTC, zverev requested changes

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/SettingsModal.tsx
> +                            defaultValue={userLink+this.state.username}
Maybe it makes sense to display updated link only after saving?

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/index.tsx
> +                }, 1000)
Please write a comment why is this timeout used here.

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/sendAddWishRequest.ts
> +export const sendAddWishRequest = (title: string, description: string, isPublic: boolean) => fetch(addNewWishUrl, {
It's great that you decided to separate API layer!
It would also be nice to encapsulate fetch details (like `await resp.json()`) and error handling here in order not to care about it in outer code.

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/sendDeleteRequest.ts
> +export const sendDeleteRequest = (wishId: string) => fetch(deleteWishUrl, {
It's great that you decided to separate API layer!
It would also be nice to encapsulate fetch details (like await resp.json()) and error handling here in order not to care about it in outer code.

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/sendEditWishRequest.ts
> +export const sendEditWishRequest = (wishId: string, wishTitle: string, wishDescription: string, isPublic: boolean) => fetch(editWishUrl, {
It's great that you decided to separate API layer!
It would also be nice to encapsulate fetch details (like await resp.json()) and error handling here in order not to care about it in outer code.

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/sendEditWishRequest.ts
> +export const sendEditWishRequest = (wishId: string, wishTitle: string, wishDescription: string, isPublic: boolean) => fetch(editWishUrl, {
It's grate that you decided to separate API layer!
It would also be nice to encapsulate fetch details (like await resp.json()) and error handling here in order not to care about it in outer code.

2021-04-08 18:38 UTC, zverev commented on src/components/AccountPage/setUsernameRequest.ts
> +export const setUsernameRequest = (username: string) => fetch(setUsernameUrl, {
It's great that you decided to separate API layer!
It would also be nice to encapsulate fetch details (like await resp.json()) and error handling here in order not to care about it in outer code.

2021-04-08 18:38 UTC, zverev commented on src/components/AuthorisePage/index.tsx
> +                    this.setState({isAuthorised: true})
You can use one `setState()` call

2021-04-08 18:38 UTC, zverev commented on src/components/AuthorisePage/index.tsx
> +                }, 1000)
Please add a comment about setTimeout function or even create a new function with a clear name.

2021-04-08 18:38 UTC, zverev commented on src/components/AuthorisePage/index.tsx
> +                }, 1000)
Please add a comment about setTimeout function or even create a new function with a clear name.

2021-04-08 18:38 UTC, zverev commented on src/components/AuthorisePage/sendAuthoriseRequest.ts
> +export const sendAuthoriseRequest = (token: string) => fetch(authRequestUrl, {
Same comment about fetch details and error handling. This function even can return a certain type!

2021-04-08 18:38 UTC, zverev commented on src/components/PublicPage/SinglePublicWish.tsx
> +    key: number,
Unused prop?

2021-04-08 18:38 UTC, zverev commented on src/components/PublicPage/index.tsx
> +                }, 1000)
Yo can create a function with a clear name `preventBlinkingBySimulatingLoading()` for example

2021-04-08 18:38 UTC, zverev commented on src/components/PublicPage/index.tsx
> +        fetch(getPublicWishesUrl+username, {
Looks like it should be moved to separate function

2021-04-08 18:38 UTC, zverev commented on src/index.css
> +html, body, #root {
MaterialUI offers it's own [way](https://material-ui.com/components/css-baseline/#global-reset) to normalise css.

2021-04-09 09:48 UTC, NZWhale commented on src/components/PublicPage/SinglePublicWish.tsx
> +    key: number,
Yes, because map method is require key prop for each element, but actually i dont need them

2021-04-09 09:53 UTC, merged